### ISSUE TITLE
rename Gpd as Groupoids

### ISSUE THREAD

**Issue by cdwensley** [gap-packages/groupoids#2]
this is planned to occur when GAP 4.9.0 becomes available

**Comment by alex-konovalov** [comment]
Isn't it time to publish the package under the new name? URLs on the page http://www.gap-system.org/Packages/gpd.html do not work since the repository has been renamed.

**Comment by fingolfin** [comment]
Indeed, I would recommend a release ASAP, if possible. Or is there anything in the new version of the package that does not work in GAP 4.8?

**Comment by cdwensley** [comment]
I am very willing to be advised on this.  My understanding was that groupoids would first appear with 4.9.0, so I have not done any work on the package for some time (at present busy working on additions to IdRel and XMod).  Of course it would suit me if the next XMod could RequirePackage(groupoids). 
> Indeed, I would recommend a release ASAP, if possible. 
> Or is there anything in the new version of the package that does not work in GAP 4.8? 
The tests appear to be OK under 4.8.7, which is not surprising since the only changes have been cosmetic.  (There is a lot to be done integrating the package with Digraphs, but no time for that at present.)
The current groupoids version is 1.51 and I will make a 1.52 before any publication. 
Please let me know what "publish the package" involves.

**Comment by fingolfin** [comment]
@cdwensley Well, if you make a release of this now / ASAP, then we can put it into GAP 4.8.8 (which right now is likely to happen before 4.9.0). And even if there is no 4.8.8, it means we can test your package with the master branch, helping us uncover compatibility problems before 4.9.0 is out.

OTOH, I see no drawbacks at all for a release -- do you?

**Comment by cdwensley** [comment]
@fingolfin  Fine - there will be a release of 1.51 tomorrow (the earlier comment was incorrect - the current version is 1.46).  I was not expecting a 4.8.8.

**Comment by alex-konovalov** [comment]
There are already a couple of dozens of packages updated since GAP 4.8.7, so I am considering cleaning up tests and making GAP 4.8.8, with only one bugfix of https://github.com/gap-system/gap/issues/1431. Please go ahead with the release!

**Comment by cdwensley** [comment]
Attempts to track down the source of the bug in InverseGeneralMapping for groupoid homomorphisms have only led to the appearance of further inconsistencies. The remedy will be to make a revised implementation on these homomorphisms - in a future release.  So 1.5.1 was not released on August 1st.  An attempted release was made today, but there was an error when running the release-tools.

**Comment by cdwensley** [comment]
Release 1.5.1 now made.

**Comment by alex-konovalov** [comment]
@cdwensley thanks - I will try to pick it up.

**Comment by alex-konovalov** [comment]
@cdwensley Thanks - picked up!
```
* groupoids - new version 1.51 discovered!!!
  ============================================
  Getting new archives from 
  https://github.com/gap-packages/groupoids/releases/download/v1.51/groupoids-\
1.51[ ".tar.gz" ]
  unpacking groupoids-1.51.tar.gz
  Validation of the info file successful!
  Package groupoids 1.51 from 06/08/2017 has dependencies:
  * NeededOtherPackages [ [ "GAPDoc", ">= 1.5.1" ], [ "fga", ">= 1.3.1" ] ]
  * GAP >=4.8.7
  * SuggestedOtherPackages [ [ "semigroups", ">= 2.8.0" ] ]
  finding text files  . . .

=====================text files==========================
groupoids-1.51/CHANGES.md
groupoids-1.51/init.g
groupoids-1.51/LICENSE.txt
groupoids-1.51/makedoc.g
groupoids-1.51/PackageInfo.g
groupoids-1.51/read.g
groupoids-1.51/README.md
groupoids-1.51/doc/bib.xml
groupoids-1.51/doc/bib.xml.bib
groupoids-1.51/doc/chap0.html
groupoids-1.51/doc/chap0.txt
groupoids-1.51/doc/chap0_mj.html
groupoids-1.51/doc/chap1.html
groupoids-1.51/doc/chap1.txt
groupoids-1.51/doc/chap1_mj.html
groupoids-1.51/doc/chap2.html
groupoids-1.51/doc/chap2.txt
groupoids-1.51/doc/chap2_mj.html
groupoids-1.51/doc/chap3.html
groupoids-1.51/doc/chap3.txt
groupoids-1.51/doc/chap3_mj.html
groupoids-1.51/doc/chap4.html
groupoids-1.51/doc/chap4.txt
groupoids-1.51/doc/chap4_mj.html
groupoids-1.51/doc/chap5.html
groupoids-1.51/doc/chap5.txt
groupoids-1.51/doc/chap5_mj.html
groupoids-1.51/doc/chap6.html
groupoids-1.51/doc/chap6.txt
groupoids-1.51/doc/chap6_mj.html
groupoids-1.51/doc/chap7.html
groupoids-1.51/doc/chap7.txt
groupoids-1.51/doc/chap7_mj.html
groupoids-1.51/doc/chap8.html
groupoids-1.51/doc/chap8.txt
groupoids-1.51/doc/chap8_mj.html
groupoids-1.51/doc/chapBib.html
groupoids-1.51/doc/chapBib.txt
groupoids-1.51/doc/chapBib_mj.html
groupoids-1.51/doc/chapInd.html
groupoids-1.51/doc/chapInd.txt
groupoids-1.51/doc/chapInd_mj.html
groupoids-1.51/doc/chooser.html
groupoids-1.51/doc/ggraph.xml
groupoids-1.51/doc/gpd.xml
groupoids-1.51/doc/gpdhom.xml
groupoids-1.51/doc/history.xml
groupoids-1.51/doc/intro.xml
groupoids-1.51/doc/lefttoc.css
groupoids-1.51/doc/manual.css
groupoids-1.51/doc/manual.xml
groupoids-1.51/doc/mwo.xml
groupoids-1.51/doc/mwohom.xml
groupoids-1.51/doc/nocolorprompt.css
groupoids-1.51/doc/ragged.css
groupoids-1.51/doc/tecnotes.xml
groupoids-1.51/doc/times.css
groupoids-1.51/doc/toggless.css
groupoids-1.51/examples/ggraph.g
groupoids-1.51/examples/gpd.g
groupoids-1.51/examples/gpdhom.g
groupoids-1.51/examples/mwo.g
groupoids-1.51/examples/mwohom.g
groupoids-1.51/examples/readall.g
groupoids-1.51/lib/gpd.gd
groupoids-1.51/lib/gpd.gi
groupoids-1.51/lib/gpdgraph.gd
groupoids-1.51/lib/gpdgraph.gi
groupoids-1.51/lib/gpdhom.gd
groupoids-1.51/lib/gpdhom.gi
groupoids-1.51/lib/grpgraph.gd
groupoids-1.51/lib/grpgraph.gi
groupoids-1.51/lib/mwo.gd
groupoids-1.51/lib/mwo.gi
groupoids-1.51/lib/mwohom.gd
groupoids-1.51/lib/mwohom.gi
groupoids-1.51/lib/util.gd
groupoids-1.51/lib/util.gi
groupoids-1.51/tst/1-mwo.tst
groupoids-1.51/tst/2-mwohom.tst
groupoids-1.51/tst/3-gpd.tst
groupoids-1.51/tst/4-gpdhom.tst
groupoids-1.51/tst/5-ggraph.tst
groupoids-1.51/tst/testall.g

=====================end of the list of text files=======
=====================binary files========================
groupoids-1.51/doc/manual.js
groupoids-1.51/doc/manual.pdf
groupoids-1.51/doc/manual.six
groupoids-1.51/doc/rainbow.js
groupoids-1.51/doc/toggless.js

=====================end of the list of binary files=====
=====================ignored files=======================

=====================end of the list of ignored files====
```
