### ISSUE TITLE
Failing tests in groupoids in GAP stable-4.10 branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/groupoids#36]
Please see https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10/jobs/546120339
```
============================OUTPUT START==============================
#I  method installed for Matrix matches more than one declaration
#I  RunPackageTests("groupoids", "1.66", "tst/testall.g", "false");
 ┌───────┐   GAP 4.dev of today
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv3
 Configuration:  gmp 6.1.2, readline
 Loaded workspace: wsp.g
 Packages:   AutoDoc 2019.05.20, Digraphs 0.15.2, FGA 1.4.0, GAPDoc 1.6.2, 
             genss 1.6.5, GRAPE 4.8.2, groupoids 1.66, IO 4.6.0, orb 4.8.2, 
             PrimGrp 3.3.2, Semigroups 3.1.3, SmallGrp 1.3, TransGrp 2.0.4
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
Architecture: x86_64-pc-linux-gnu-default64-kv3
testing: /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/extra/auto-gpd.\
tst
########> Diff in /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/extra/\
auto-gpd.tst:73
# Input is:
A123 := AutomorphismGroupoidOfGroupoid( G123 );; 
# Expected output:
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `ObjectList' on 1 arguments
########
########> Diff in /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/extra/\
auto-gpd.tst:74
# Input is:
SetName( A123, "A123" ); 
# Expected output:
# But found:
Error, Variable: 'A123' must have a value
########
    1044 ms (116 ms GC) and 201MB allocated for auto-gpd.tst
testing: /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/extra/autos.tst
     224 ms (20 ms GC) and 39.8MB allocated for autos.tst
testing: /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/extra/autos2.ts\
t
      24 ms (0 ms GC) and 3.90MB allocated for autos2.tst
testing: /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/extra/cosets.ts\
t
########> Diff in /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/extra/\
cosets.tst:25
# Input is:
PrintSelection( star7, 24, 24 );
# Expected output:
24 : [(2,4,3) : -7 -> -6]
48 : [(1,5,4,2) : -7 -> -7]
72 : [(1,5)(3,4) : -7 -> -8]
96 : [(1,2)(3,5) : -7 -> -9]
120 : [(1,2,3)(4,5) : -7 -> -5]
# But found:
Error, Variable: 'PrintSelection' must have a value
########
########> Diff in /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/extra/\
cosets.tst:36
# Input is:
PrintSelection( costar6, 24, 24 );
# Expected output:
24 : [(3,5,4) : -6 -> -6]
48 : [(1,3,2,4) : -7 -> -6]
72 : [(1,4,2,5,3) : -8 -> -6]
96 : [(1,5,2,3,4) : -9 -> -6]
120 : [(1,2,4,3) : -5 -> -6]
# But found:
Error, Variable: 'PrintSelection' must have a value
########
########> Diff in /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/extra/\
cosets.tst:46
# Input is:
PrintSelection( hs85, 1, 6 );
# Expected output:
1 : [(1,5,4) : -8 -> -5]
7 : [(1,3,5,2,4) : -8 -> -5]
13 : [(1,4)(2,3) : -8 -> -5]
19 : [(1,2,5,3,4) : -8 -> -5]
# But found:
Error, Variable: 'PrintSelection' must have a value
########
     168 ms (32 ms GC) and 58.1MB allocated for cosets.tst
testing: /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/manual/ggraph.t\
st
     192 ms (72 ms GC) and 28.5MB allocated for ggraph.tst
testing: /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/extra/gpd-isos.\
tst
      20 ms (0 ms GC) and 3.95MB allocated for gpd-isos.tst
testing: /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/manual/gpd.tst
      88 ms (60 ms GC) and 5.94MB allocated for gpd.tst
testing: /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/manual/gpdaut.t\
st
    1280 ms (156 ms GC) and 268MB allocated for gpdaut.tst
testing: /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/manual/gpdhom.t\
st
      76 ms (56 ms GC) and 3.26MB allocated for gpdhom.tst
testing: /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/extra/homs.tst
     892 ms (60 ms GC) and 85.9MB allocated for homs.tst
testing: /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/extra/isos.tst
       8 ms (0 ms GC) and 764KB allocated for isos.tst
testing: /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/manual/mwo.tst
      72 ms (60 ms GC) and 1.67MB allocated for mwo.tst
testing: /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/manual/mwohom.t\
st
      64 ms (56 ms GC) and 2.87MB allocated for mwohom.tst
testing: /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/extra/nicemap.t\
st
     216 ms (24 ms GC) and 36.9MB allocated for nicemap.tst
testing: /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/extra/rt-act.ts\
t
       0 ms (0 ms GC) and 472KB allocated for rt-act.tst
testing: /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/extra/subgpds.t\
st
       8 ms (0 ms GC) and 1.90MB allocated for subgpds.tst
-----------------------------------
total      4376 ms (712 ms GC) and 744MB allocated
              5 failures in 2 of 16 files
#I  Errors detected while testing
============================OUTPUT END================================
```

**Comment by cdwensley** [comment]
Dear Alex 

Is it my imagination, or has the testing regime become a little unstable this weekend? 

The sudden Utils error - apparently due to different ways of sorting lists of images of permutation group homomorphisms - has been fixed. 

The first groupoids error, 
> testing: /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/extra/auto-gpd.tst
> ########> Diff in /home/gap/inst/gap-stable-4.10/pkg/groupoids-1.66/tst/extra/auto-gpd.tst:73
> # Input is:
> A123 := AutomorphismGroupoidOfGroupoid( G123 );; 
> # Expected output:
> # But found:
> Error, no method found! For debugging hints type ?Recovery from NoMethodFound
> Error, no 1st choice method found for `ObjectList' on 1 arguments
seems very odd, but has gone away in today’s test. 
That was after I added Utils to the required packages for groupoids. 

But then there were a host of new errors, e.g.  
testing: /home/travis/build/gap-packages/groupoids/gaproot/pkg/groupoids/tst/extra/gpd-isos.tst
########> Diff in /home/travis/build/gap-packages/groupoids/gaproot/pkg/groupoids/tst/extra/gpd-isos.tst:42
# Input is:
z2 := ImageElm( isos2[3], (2,3) );
# Expected output:
F1
# But found:
F2^-1
due to changes in isomorphisms from permutation to fp groups. 
Will this vary with the set of packages loaded, or is it safe to chenge the tests to show the new output? 

Best wishes, Chris

**Comment by alex-konovalov** [comment]
It's a nightly build of docker containers - could be that some changes happened in the meantime. It's useful to provide URL to point to a particular build.

**Comment by cdwensley** [comment]
Dear Alex 

OK - I’ll bear in mind that one night’s failure might disappear the next night. 

Looking at last night’s tests, it appears that the changes I committed yesterday have not been taken into account. 
Is it necessary to make such commits using PRs for them to be noticed, or were they made too late and I should wait another day? 

Thanks, Chris

**Comment by alex-konovalov** [comment]
Hello @cdwensley - this does not give me enough info to explain, could you post a link to the build please?

**Comment by cdwensley** [comment]
I was just enquiringing about the general procedure on travis.
In this case I was looking at:   https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10/jobs/546386254
which was still not loading Utils, whereas I had committed a change to PackageInfo.g before 2pm yesterday: 
https://github.com/gap-packages/groupoids/commit/a6418f5fd9962715c0fb289177f438e8247273cf

**Comment by alex-konovalov** [comment]
That's correct because https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10/ uses fixed package archive namely https://www.gap-system.org/pub/gap/gap4pkgs/packages-stable-4.10.tar.gz. If you want to see how the development version of Utils or Groupoids behaves, you should see https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10-devel but that one will clone Utils repo and try to load it with Groupoids from `gap4pkgs` archive, and vice versa. If you need to check related package updates together, you need to set up a `prerequsites.sh` script as explained in https://github.com/gap-infra/gap-docker-pkg-tests-master-devel README.

**Comment by alex-konovalov** [comment]
In other words, "the general procedure on travis" is too generic question - Travis can be set up in multiple ways: tests for each commit and PR, or cron jobs that run daily/weekly/monthly, tests that pull the latest state of the repository, or tests that use the most recent Docker container, etc., and we use a variety of approaches in different places.

**Comment by alex-konovalov** [comment]
In particular, https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10/  is based on https://github.com/gap-infra/gap-docker-pkg-tests-stable-4.10 which has a README which explains what's the setting there.

**Comment by cdwensley** [comment]
Made changes to groupoids tests, forcing s3f (the fp-group version of s3) to be the group with presentation f2/[f2.1^3,f2.2^2,(f2.1*f2.2)^2], so that tests now pass in both 4.10.2 and gapdev.
