### ISSUE TITLE
Failing regression tests in Travis nightly builds for GAP packages

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/groupoids#8]
This problem is apparently caused by Semgroups now working properly with gcc version that is present in the Docker container. Hence for now groupoids tests are moved to the "staging" Travis nightly builds for standard test in GAP packages (https://travis-ci.org/gap-system/)

**Comment by alex-konovalov** [comment]
An example of the failing build is https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9-staging/jobs/336971279. The test log reports `CRASH` for all there cases, and that's a correct report - the test does not finish because the GAP session terminates with
```
terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
```
I don't think this is a problem in groupoids (and I also can see its tests passing e.g. in our Jenkins builds), but because it is now in staging tests, please continue to monitor tests status yourself.

**Comment by cdwensley** [comment]
Removed Semigroups from the list SuggestedOtherPackages (temporarily?).
