### ISSUE TITLE
Setup Travis CI and CodeCov tests

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/groupoids#9]
We need to set them up - this will be useful, and also will give some relief if they will not have the problem reported in #8.

**Comment by alex-konovalov** [comment]
The first build passes when  it does not involve building Semigroups: https://travis-ci.org/gap-packages/groupoids/builds/338053667

**Comment by alex-konovalov** [comment]
The 2nd build of #10 includes Semigroups and also passes: https://travis-ci.org/gap-packages/groupoids/builds/338057724

**Comment by alex-konovalov** [comment]
@cdwensley I think you can now merge #10 and close #9.

**Comment by cdwensley** [comment]
I believe I have merged PR #10 which closed Issue #9, though I have no idea what the new files in the new folder /scripts do.  Can issue #8 now be closed, or is this PR just a means towards finding out why the crashes occur?

**Comment by alex-konovalov** [comment]
@cdwensley thanks. PR #10 is a good thing on its own, not just to investigate #8. With #10, from now on every commit (to master branch or in a pull request) will be processed by Travis CI and CodeCov to run standard tests of the package and collect code coverage information. It's so useful tool that I am almost stopped to do direct commits to master to all my packages - I do a pull request, polish it until tests pass, if necessary, and then rebase on master to keep the revisions history linear.

The content of these files from `scripts` is now duplicated in many packages using them (including Example package, modulo waiting PR for an updated version of them). Perhaps we need to write more comments there, in particular about minimal adjustments that they may need if a tested package needs more packages compiled. It may be nice to use the same setup for all your other packages eventually...

As for #8, I suggest to keep it open as a reminder.
